import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 1. IT loyiha ishlab chiqish
// 2. Startap uchun IT yechimlar
// 3. Onlayn biznes uchun websayt kerak
// 4. IT loyiha boshqaruvi xizmati
// 5. IT jamoa kerak 
// 6. web dasturlash xizmatlari
// 7. mobil ilova ishlab chiqish
// 8. Sayt yasash xizmati
// 9. Website buyurtma berish
// 10. O’zbekistonda top PM lar
// 11. O’zbekistonda IT loyiha boshqarish
// 12. IT Loyiha boshqaruvchi
// 13. IT loyiha ishlab chiqish narxi
// 14. Biznesga sayt kerak
// 15. Website buyurtma

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
